"""initial schema: scopes, identity, profiles, prompts, waitlist

Revision ID: 68a2ddf41c72
Revises: 
Create Date: 2026-09-12 13:42:23.503817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '68a2ddf41c72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender_identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('default_visible_as', sa.JSON(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_library',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('emphasis', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_library_category'), ['category'], unique=False)

    op.create_table('scopes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('email_domains', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scopes_slug'), ['slug'], unique=True)

    op.create_table('sexualities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('former_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('email_hash', sa.String(), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('former_members', schema=None) as batch_op:
        batch_op.create_index('ix_former_member_lookup', ['scope_id', 'email_hash'], unique=False)

    op.create_table('segment_caps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('cap', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'segment', name='uq_segment_cap')
    )
    with op.batch_alter_table('segment_caps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segment_caps_scope_id'), ['scope_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('scope_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cap_segment', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index('ix_users_scope_segment_status', ['scope_id', 'cap_segment', 'status'], unique=False)

    op.create_table('email_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('match_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_a_id', sa.String(), nullable=False),
    sa.Column('user_b_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_records', schema=None) as batch_op:
        batch_op.create_index('ix_match_records_user_a', ['user_a_id'], unique=False)
        batch_op.create_index('ix_match_records_user_b', ['user_b_id'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('moderation_passed', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gender_identity_id', sa.String(), nullable=True),
    sa.Column('custom_gender', sa.String(), nullable=True),
    sa.Column('sexuality_id', sa.String(), nullable=True),
    sa.Column('custom_sexuality', sa.String(), nullable=True),
    sa.Column('pronouns', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('ethnicities', sa.JSON(), nullable=False),
    sa.Column('children', sa.String(), nullable=True),
    sa.Column('family_plans', sa.String(), nullable=True),
    sa.Column('pets', sa.String(), nullable=True),
    sa.Column('zodiac', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('workplace', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('religion', sa.String(), nullable=True),
    sa.Column('politics', sa.String(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('dating_intentions', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('drinking', sa.String(), nullable=True),
    sa.Column('smoking', sa.String(), nullable=True),
    sa.Column('marijuana', sa.String(), nullable=True),
    sa.Column('drugs', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gender_identity_id'], ['gender_identities.id'], ),
    sa.ForeignKeyConstraint(['sexuality_id'], ['sexualities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('prompt_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('audio_key', sa.String(), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot', name='uq_prompt_slot')
    )
    with op.batch_alter_table('prompt_responses', schema=None) as batch_op:
        batch_op.create_index('ix_prompt_responses_user', ['user_id'], unique=False)

    op.create_table('user_interested_in',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'segment'),
    sa.UniqueConstraint('user_id', 'segment', name='uq_interested_in')
    )
    op.create_table('user_visible_as',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'segment'),
    sa.UniqueConstraint('user_id', 'segment', name='uq_visible_as')
    )
    op.create_table('waitlist_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_waitlist_user')
    )
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.create_index('ix_waitlist_queue', ['scope_id', 'segment', 'status', 'joined_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('from_user_id', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['match_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_match_created', ['match_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_match_id'))
        batch_op.drop_index('ix_chat_messages_match_created')

    op.drop_table('chat_messages')
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_waitlist_queue')

    op.drop_table('waitlist_entries')
    op.drop_table('user_visible_as')
    op.drop_table('user_interested_in')
    with op.batch_alter_table('prompt_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_responses_user')

    op.drop_table('prompt_responses')
    op.drop_table('profiles')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_user_id'))

    op.drop_table('photos')
    with op.batch_alter_table('match_records', schema=None) as batch_op:
        batch_op.drop_index('ix_match_records_user_b')
        batch_op.drop_index('ix_match_records_user_a')

    op.drop_table('match_records')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_token_hash'))

    op.drop_table('email_verifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_scope_segment_status')
        batch_op.drop_index(batch_op.f('ix_users_scope_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('segment_caps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segment_caps_scope_id'))

    op.drop_table('segment_caps')
    with op.batch_alter_table('former_members', schema=None) as batch_op:
        batch_op.drop_index('ix_former_member_lookup')

    op.drop_table('former_members')
    op.drop_table('sexualities')
    with op.batch_alter_table('scopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scopes_slug'))

    op.drop_table('scopes')
    with op.batch_alter_table('prompt_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_library_category'))

    op.drop_table('prompt_library')
    op.drop_table('gender_identities')
    # ### end Alembic commands ###
