"""phase 05: safety and rate limits

Revision ID: ee7f324fc0ac
Revises: 
Create Date: 2026-09-12 23:39:10.070711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ee7f324fc0ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before any vector column is created. Supabase ships
    # the extension; this only enables it for this database.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender_identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('default_visible_as', sa.JSON(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_claim', ['status', 'run_after'], unique=False)
        batch_op.create_index('ix_jobs_subject', ['subject_id'], unique=False)

    op.create_table('prompt_library',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('emphasis', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_library_category'), ['category'], unique=False)

    op.create_table('rate_limit_windows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 'window_start', name='uq_rate_limit_window')
    )
    with op.batch_alter_table('rate_limit_windows', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_sweep', ['window_start'], unique=False)

    op.create_table('scopes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('email_domains', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scopes_slug'), ['slug'], unique=True)

    op.create_table('sexualities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('former_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('email_hash', sa.String(), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('former_members', schema=None) as batch_op:
        batch_op.create_index('ix_former_member_lookup', ['scope_id', 'email_hash'], unique=False)

    op.create_table('segment_caps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('cap', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'segment', name='uq_segment_cap')
    )
    with op.batch_alter_table('segment_caps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segment_caps_scope_id'), ['scope_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('scope_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cap_segment', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index('ix_users_scope_segment_status', ['scope_id', 'cap_segment', 'status'], unique=False)

    op.create_table('affinities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('viewer_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('shown', sa.Integer(), nullable=False),
    sa.Column('picked', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('confidence_low', sa.Float(), nullable=False),
    sa.Column('confidence_high', sa.Float(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viewer_id', 'subject_id', name='uq_affinity_viewer_subject')
    )
    with op.batch_alter_table('affinities', schema=None) as batch_op:
        batch_op.create_index('ix_affinities_subject', ['subject_id'], unique=False)
        batch_op.create_index('ix_affinities_viewer_state', ['viewer_id', 'state'], unique=False)

    op.create_table('blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('blocker_id', sa.String(), nullable=False),
    sa.Column('blocked_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_block_pair')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index('ix_blocks_blocked', ['blocked_id'], unique=False)
        batch_op.create_index('ix_blocks_blocker', ['blocker_id'], unique=False)

    op.create_table('connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_a_id', sa.String(), nullable=False),
    sa.Column('user_b_id', sa.String(), nullable=False),
    sa.Column('connection_key', sa.String(), nullable=False),
    sa.Column('initiator_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_key', name='uq_connection_key')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index('ix_connections_user_a', ['user_a_id', 'status'], unique=False)
        batch_op.create_index('ix_connections_user_b', ['user_b_id', 'status'], unique=False)

    op.create_table('email_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('media_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('public_url', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('gate_reason', sa.String(), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('det_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key', name='uq_media_object_key')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_media_user_kind', ['user_id', 'kind', 'status'], unique=False)

    op.create_table('pairings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('viewer_id', sa.String(), nullable=False),
    sa.Column('subject_a_id', sa.String(), nullable=False),
    sa.Column('subject_b_id', sa.String(), nullable=False),
    sa.Column('pair_key', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('round', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chosen_id', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chosen_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viewer_id', 'pair_key', 'round', name='uq_pairing_viewer_pair_round')
    )
    with op.batch_alter_table('pairings', schema=None) as batch_op:
        batch_op.create_index('ix_pairings_due', ['status', 'round', 'due_at'], unique=False)
        batch_op.create_index('ix_pairings_serve', ['viewer_id', 'status', 'round', 'position'], unique=False)
        batch_op.create_index('ix_pairings_subject_a', ['subject_a_id'], unique=False)
        batch_op.create_index('ix_pairings_subject_b', ['subject_b_id'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gender_identity_id', sa.String(), nullable=True),
    sa.Column('custom_gender', sa.String(), nullable=True),
    sa.Column('sexuality_id', sa.String(), nullable=True),
    sa.Column('custom_sexuality', sa.String(), nullable=True),
    sa.Column('pronouns', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('ethnicities', sa.JSON(), nullable=False),
    sa.Column('children', sa.String(), nullable=True),
    sa.Column('family_plans', sa.String(), nullable=True),
    sa.Column('pets', sa.String(), nullable=True),
    sa.Column('zodiac', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('workplace', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('religion', sa.String(), nullable=True),
    sa.Column('politics', sa.String(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('dating_intentions', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('drinking', sa.String(), nullable=True),
    sa.Column('smoking', sa.String(), nullable=True),
    sa.Column('marijuana', sa.String(), nullable=True),
    sa.Column('drugs', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gender_identity_id'], ['gender_identities.id'], ),
    sa.ForeignKeyConstraint(['sexuality_id'], ['sexualities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('prompt_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('audio_key', sa.String(), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot', name='uq_prompt_slot')
    )
    with op.batch_alter_table('prompt_responses', schema=None) as batch_op:
        batch_op.create_index('ix_prompt_responses_user', ['user_id'], unique=False)

    op.create_table('ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('audience_segment', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('comparison_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'audience_segment', 'kind', name='uq_rating_subject_segment_kind')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index('ix_ratings_subject', ['subject_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reporter_id', sa.String(), nullable=True),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_queue', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_reports_subject', ['subject_id'], unique=False)

    op.create_table('user_interested_in',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'segment'),
    sa.UniqueConstraint('user_id', 'segment', name='uq_interested_in')
    )
    op.create_table('user_visible_as',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'segment'),
    sa.UniqueConstraint('user_id', 'segment', name='uq_visible_as')
    )
    op.create_table('viewer_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('viewer_id', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('weights', pgvector.sqlalchemy.vector.VECTOR(dim=512).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viewer_id', 'segment', name='uq_viewer_preference')
    )
    op.create_table('waitlist_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_waitlist_user')
    )
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.create_index('ix_waitlist_queue', ['scope_id', 'segment', 'status', 'joined_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('from_user_id', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_connection_created', ['connection_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_connection_id'), ['connection_id'], unique=False)

    op.create_table('profile_embeddings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('face_vector', pgvector.sqlalchemy.vector.VECTOR(dim=512).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('face_source_id', sa.String(), nullable=True),
    sa.Column('voice_vector', pgvector.sqlalchemy.vector.VECTOR(dim=192).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('text_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_language', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['face_source_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_embeddings')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_connection_id'))
        batch_op.drop_index('ix_chat_messages_connection_created')

    op.drop_table('chat_messages')
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_waitlist_queue')

    op.drop_table('waitlist_entries')
    op.drop_table('viewer_preferences')
    op.drop_table('user_visible_as')
    op.drop_table('user_interested_in')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_subject')
        batch_op.drop_index('ix_reports_queue')

    op.drop_table('reports')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index('ix_ratings_subject')

    op.drop_table('ratings')
    with op.batch_alter_table('prompt_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_responses_user')

    op.drop_table('prompt_responses')
    op.drop_table('profiles')
    with op.batch_alter_table('pairings', schema=None) as batch_op:
        batch_op.drop_index('ix_pairings_subject_b')
        batch_op.drop_index('ix_pairings_subject_a')
        batch_op.drop_index('ix_pairings_serve')
        batch_op.drop_index('ix_pairings_due')

    op.drop_table('pairings')
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_media_user_kind')
        batch_op.drop_index(batch_op.f('ix_media_assets_user_id'))

    op.drop_table('media_assets')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_token_hash'))

    op.drop_table('email_verifications')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index('ix_connections_user_b')
        batch_op.drop_index('ix_connections_user_a')

    op.drop_table('connections')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index('ix_blocks_blocker')
        batch_op.drop_index('ix_blocks_blocked')

    op.drop_table('blocks')
    with op.batch_alter_table('affinities', schema=None) as batch_op:
        batch_op.drop_index('ix_affinities_viewer_state')
        batch_op.drop_index('ix_affinities_subject')

    op.drop_table('affinities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_scope_segment_status')
        batch_op.drop_index(batch_op.f('ix_users_scope_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('segment_caps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segment_caps_scope_id'))

    op.drop_table('segment_caps')
    with op.batch_alter_table('former_members', schema=None) as batch_op:
        batch_op.drop_index('ix_former_member_lookup')

    op.drop_table('former_members')
    op.drop_table('sexualities')
    with op.batch_alter_table('scopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scopes_slug'))

    op.drop_table('scopes')
    with op.batch_alter_table('rate_limit_windows', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_sweep')

    op.drop_table('rate_limit_windows')
    with op.batch_alter_table('prompt_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_library_category'))

    op.drop_table('prompt_library')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_subject')
        batch_op.drop_index('ix_jobs_claim')

    op.drop_table('jobs')
    op.drop_table('gender_identities')
    # ### end Alembic commands ###
